# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_recomp_say_less"

# Version of this mod.
version = "0.1.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Say Less"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
WARNING: Early release. If I've messed up the logic, it'll probably softlock you. lol. \
Please report any bugs you find! \
\
Makes people say less - takes you straight to the decisions without all of the lore. \
\
Affected NPCs: \
- Banker \
More coming soon! (tingle next) \
\
For more details, see https://github.com/Jazzkid0/mm-say-less."""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Makes NPCs say less, so you can get on and save Termina."

# Authors of this mod.
authors = [ "Jazzkid" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
    # "MM_EZ_Text_Replacer_API:2.0.1"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_recomp_say_less"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.dds" ]

# [[manifest.config_options]]
# id = "say_less_banker"
# name = "Banker"
# description = "Make the banker say less (NOT CURRENTLY FUNCTIONAL)"
# type = "Enum"
# options = [ "Off", "On" ]
# default = "On"
